using System;
using System.Collections.Generic;
using WalkGame.Application.Ux;
using WalkGame.Domain.Activity;

namespace WalkGame.Application.ReadModels
{
    /// <summary>
    /// Support/diagnostics projection (Workstream D, D-044): ONLY privacy-safe operational
    /// facts — classified enums, bounded counters, timestamps, and adapter-owned technical
    /// detail strings. By construction it contains no activity records, no payloads, no
    /// raw exception text generated by this codebase. Reading is side-effect free; the
    /// DiagnosticsVisible preference gates presentation display, not the data itself.
    /// </summary>
    public sealed class DiagnosticsReadModel
    {
        public DateTimeOffset GeneratedAtUtc { get; }

        /// <summary>Outcome of the last boot attempt on this session object.</summary>
        public DiagnosticsBootOutcome BootOutcome { get; }

        /// <summary>True when boot succeeded only via the backup generation (D-040 path).</summary>
        public bool RecoveredFromBackup { get; }

        /// <summary>Structured category of the last failed decode attempt during boot.</summary>
        public CodecFailureCategory LastBootCodecFailure { get; }

        /// <summary>Migrations applied while decoding at boot (empty when none were needed).</summary>
        public IReadOnlyList<string> AppliedMigrationsAtBoot { get; }

        public int SchemaVersion { get; }

        public string RegionId { get; }

        /// <summary>Durable reconciliation watermark: latest activity end trusted so far.</summary>
        public DateTimeOffset IngestionCheckpointUtc { get; }

        /// <summary>Floor of (read time − watermark) in whole days; clamped at zero.</summary>
        public long CheckpointWatermarkAgeDays { get; }

        public int ProcessedRecordCount { get; }

        /// <summary>Lifetime credited Vitality per the durable processed-record ledger.</summary>
        public long LifetimeVitalityCredited { get; }

        /// <summary>Cumulative reversals policy refused to claw back (visible forever, D-029).</summary>
        public long UnappliedReversalVitality { get; }

        public DiagnosticsIngestionRow? LastIngestion { get; }

        public UxPreferencesLoadOutcome PreferencesLoadOutcome { get; }

        /// <summary>Bounded technical detail from the preferences store load (support only).</summary>
        public string? PreferencesLoadDetail { get; }

        /// <summary>Bounded adapter-owned technical detail (support only, never player copy).</summary>
        public string? ConnectionTechnicalDetail { get; }

        public DiagnosticsReadModel(
            DateTimeOffset generatedAtUtc,
            DiagnosticsBootOutcome bootOutcome,
            bool recoveredFromBackup,
            CodecFailureCategory lastBootCodecFailure,
            IReadOnlyList<string> appliedMigrationsAtBoot,
            int schemaVersion,
            string regionId,
            DateTimeOffset ingestionCheckpointUtc,
            long checkpointWatermarkAgeDays,
            int processedRecordCount,
            long lifetimeVitalityCredited,
            long unappliedReversalVitality,
            DiagnosticsIngestionRow? lastIngestion,
            UxPreferencesLoadOutcome preferencesLoadOutcome,
            string? preferencesLoadDetail,
            string? connectionTechnicalDetail)
        {
            GeneratedAtUtc = generatedAtUtc;
            BootOutcome = bootOutcome;
            RecoveredFromBackup = recoveredFromBackup;
            LastBootCodecFailure = lastBootCodecFailure;
            AppliedMigrationsAtBoot = appliedMigrationsAtBoot;
            SchemaVersion = schemaVersion;
            RegionId = regionId;
            IngestionCheckpointUtc = ingestionCheckpointUtc;
            CheckpointWatermarkAgeDays = checkpointWatermarkAgeDays;
            ProcessedRecordCount = processedRecordCount;
            LifetimeVitalityCredited = lifetimeVitalityCredited;
            UnappliedReversalVitality = unappliedReversalVitality;
            LastIngestion = lastIngestion;
            PreferencesLoadOutcome = preferencesLoadOutcome;
            PreferencesLoadDetail = preferencesLoadDetail;
            ConnectionTechnicalDetail = connectionTechnicalDetail;
        }
    }

    /// <summary>Bounded counter row describing the most recent ingestion batch.</summary>
    public sealed class DiagnosticsIngestionRow
    {
        public IngestionOutcomeKind Outcome { get; }
        public DateTimeOffset CompletedAtUtc { get; }
        public int TotalReceived { get; }
        public int Accepted { get; }
        public int Rejected { get; }
        public int DuplicatesIgnored { get; }
        public int CorrectionsApplied { get; }
        public int DeletionsApplied { get; }
        public long VitalityCredited { get; }
        public long UnappliedReversalVitality { get; }

        /// <summary>Stable error-category classification; never a raw exception message.</summary>
        public string? ErrorCategory { get; }

        private DiagnosticsIngestionRow(
            IngestionOutcomeKind outcome, DateTimeOffset completedAtUtc,
            int totalReceived, int accepted, int rejected, int duplicatesIgnored,
            int correctionsApplied, int deletionsApplied,
            long vitalityCredited, long unappliedReversalVitality, string? errorCategory)
        {
            Outcome = outcome;
            CompletedAtUtc = completedAtUtc;
            TotalReceived = totalReceived;
            Accepted = accepted;
            Rejected = rejected;
            DuplicatesIgnored = duplicatesIgnored;
            CorrectionsApplied = correctionsApplied;
            DeletionsApplied = deletionsApplied;
            VitalityCredited = vitalityCredited;
            UnappliedReversalVitality = unappliedReversalVitality;
            ErrorCategory = errorCategory;
        }

        internal static DiagnosticsIngestionRow FromState(IngestionOutcomeState state) =>
            new DiagnosticsIngestionRow(
                state.Outcome, state.CompletedAtUtc,
                state.TotalReceived, state.Accepted, state.Rejected, state.DuplicatesIgnored,
                state.CorrectionsApplied, state.DeletionsApplied,
                state.VitalityCredited, state.UnappliedReversalVitality, state.ErrorCategory);
    }
}
